
INSERT INTO confiedy_ui.curso
(id,ciclo, codigo, descripcion, duracion, imagen_curso, maximo_estudiantes, nombre, universidad_id)
VALUES(1,"1", "MAT155", "El curso permitirá a los estudiantes reconocer la importancia de las matemáticas en diversas actividades de la vida cotidiana, así como en distintos campos del conocimiento y contribuirá a desarrollar el razonamiento lógico. Esto se hará a través de situaciones que correspondan a contextos propios de las distintas especialidades y cuyo análisis requiera del empleo de conceptos matemáticos fundamentales. A partir de su intervención en actividades de resolución de problemas matemáticos, los estudiantes analizarán la información brindada e identificarán las técnicas y teorías matemáticas que les permitirán resolver el problema. En este proceso se hará uso de la rigurosidad matemática y se empleará el lenguaje simbólico para comunicar los procedimientos y resultados.", "4 horas", "https://confiedy.com/images/courses/courses1.jpg", "5", "Matemática Básica", 1);

INSERT INTO confiedy_ui.curso
(id,ciclo, codigo, descripcion, duracion, imagen_curso, maximo_estudiantes, nombre, universidad_id)
VALUES(2,"1","1MAT25","Se brindan los fundamentos matemáticos de cálculo diferencial en una variable. Este curso abarca los siguientes temas: sistema de números reales, relaciones y funciones. Funciones de una variable, concepto de límite; tasa de cambio y derivadas, derivada y pendiente de una curva, teoremas sobre límites; continuidad y diferenciabilidad de funciones, reglas de diferenciación. Optimización en una variable. Integración, métodos de integración. La integral definida como suma de Riemann. Integrales impropias.", "4 horas","https://www.confiedy.com/images/courses/courses2.jpg", "5", "Matemática para Economía y Finanzas 1", 1);

INSERT INTO confiedy_ui.curso
(id,ciclo, codigo, descripcion, duracion, imagen_curso, maximo_estudiantes, nombre, universidad_id)
VALUES(3,"7","1GES11","El curso se centra en presentar los métodos matemáticos aplicados a las finanzas que permiten determinar el costo del dinero, la valorización de instrumentos financieros y las distintas formas de reembolso de obligaciones en operaciones financieras. Los estudiantes aprenderán a valorar y evaluar decisiones de inversión y financiamiento en el ámbito de las finanzas personales y empresariales.", "4 horas", "https://confiedy.com/images/courses/courses3.jpg", "5", "Matemática Financiera", 1);

INSERT INTO confiedy_ui.curso
(id,ciclo, codigo, descripcion, duracion, imagen_curso, maximo_estudiantes, nombre, universidad_id)
VALUES(4,"2","1EST10","El curso presenta las bases formales de los modelos probabilísticos asociados con el análisis estadístico de datos y luego introduce al alumno en el uso de estos modelos para la toma de decisiones en condiciones de incertidumbre con datos provenientes de muestras, aplicando técnicas estadísticas descriptivas e inferenciales. Se estudia el muestreo, estadísticas de tendencia central y de dispersión; números índice e introducción a las series de tiempo.", "4 horas", "https://www.confiedy.com/images/courses/courses1.jpg", "5", "Introducción a la Estadística y Probabilidad", 1);

INSERT INTO confiedy_ui.curso
(id,ciclo, codigo, descripcion, duracion, imagen_curso, maximo_estudiantes, nombre, universidad_id)
VALUES(5,"2","EST103","El enfoque del curso será práctico con énfasis en una adecuada interpretación de los resultados numéricos obtenidos, relacionándolos con el contexto específico de los problemas planteados. Se abordarán los siguientes temas generales: Análisis descriptivo de datos, probabilidades, modelos de probabilidad y estimación de parámetros.", "4 horas", "https://www.confiedy.com/images/courses/courses2.jpg", "5", "Estadística", 1);

INSERT INTO confiedy_ui.curso
(id,ciclo, codigo, descripcion, duracion, imagen_curso, maximo_estudiantes, nombre, universidad_id)
VALUES(6,"1","MAT124","El curso ofrece una introducción a las funciones matemáticas y a algunas aplicaciones de las mismas a través de los siguientes temas: sistemas de números reales; elementos de geometría analítica; gráficas de ecuaciones e inecuaciones lineales y cuadráticas en dos variables reales; introducción a la programación lineal; funciones reales de variable real: lineales, cuadráticas, polinomiales, racionales; modelo básico del inventario; funciones exponenciales y logarítmicas; sucesiones; sumatorias; elementos de matemática financiera.", "4 horas", "https://www.confiedy.com/images/courses/courses3.jpg", "5", "Matemática 1", 1);

INSERT INTO confiedy_ui.curso
(id,ciclo, codigo, descripcion, duracion, imagen_curso, maximo_estudiantes, nombre, universidad_id)
VALUES(7,"2","MAT125","Este curso es el primero de una serie destinada a sentar las bases matemáticas de las ciencias de Gestión y Alta Dirección, y de Contabilidad. Sus temas son: límite de funciones reales de una variable real, continuidad de funciones reales de una variable real, derivada de funciones reales de una variable real, aplicaciones de la derivada, integración de funciones reales de una variable real y aplicaciones de la integración", "4 horas", "https://www.confiedy.com/images/courses/courses1.jpg", "5", "Matemática 2", 1);

INSERT INTO confiedy_ui.curso
(id,ciclo, codigo, descripcion, duracion, imagen_curso, maximo_estudiantes, nombre, universidad_id)
VALUES(9,"8","GES244","Es un curso teórico-práctico, forma parte del eje de Gestión Financiera y se centra en la valorización de inversiones y la estructura de financiamiento de las organizaciones. Capacita a los y las estudiantes en la evaluación y selección de alternativas de inversión que generen valor mediante el uso de diversas metodologías, así como la estructuración de distintas formas de financiamiento de las inversiones y la identificación de la mejor alternativa. Se estudian los criterios técnicos basados en el valor temporal del dinero para evaluar inversiones, el costo del capital, la diferencia entre evaluación económica y evaluación financiera, los proyectos independientes y los proyectos mutuamente excluyentes, la relación entre el costo de capital con la estructura de financiamiento y el impacto de los impuestos en las decisiones de inversión y financiamiento", "4 horas", "https://www.confiedy.com/images/courses/courses2.jpg", "5","Finanzas 1", 1);

INSERT INTO confiedy_ui.curso
(id,ciclo, codigo, descripcion, duracion, imagen_curso, maximo_estudiantes, nombre, universidad_id)
VALUES(10,"1","1MAT04","Es un curso teórico-práctico que aporta al logro de la competencia general aprender a aprender porque desarrolla la capacidad de aplicar conocimientos de matemáticas para la resolución de problemas. En este curso, se abarca los siguientes tres temas: geometría analítica, con las definiciones y propiedades importantes de la recta, circunferencia, parábola, elipse e hipérbola, y la rotación de ejes; álgebra matricial, que comprende las definiciones y operaciones de vectores y matrices aplicados en la resolución de sistemas lineales homogéneos y no homogéneos, y que, además, incluye el cálculo de vectores y valores propios de una matriz; números complejos y sus operaciones básicas. En este curso, se propone la aplicación de todos estos temas en la resolución de problemas intramatemáticos y extramatemáticos.", "4 horas", "https://www.confiedy.com/images/courses/courses12.jpg", "5","Álgebra Matricial y Geometría Analítica", 1);

INSERT INTO confiedy_ui.curso
(id,ciclo, codigo, descripcion, duracion, imagen_curso, maximo_estudiantes, nombre, universidad_id)
VALUES(11,"1","1MAT05","En este curso, se utiliza los principios básicos de la lógica matemática para analizar, demostrar conjeturas y realizar demostraciones indirectas o directas. Asimismo, se aplica el principio de inducción matemática como un método de demostración directa y se resuelve inecuaciones usando propiedades de desigualdades en los números reales. Además, se aborda los conceptos y propiedades fundamentales de las funciones reales de variable real, tales como las funciones lineales, polinómicas, racionales, valor absoluto, exponenciales, logarítmicas, trigonométricas y trigonométricas inversas. También, se profundiza sobre los conocimientos de estas funciones aplicando operaciones con funciones, la composición de funciones, función inyectiva y función inversa en la resolución de problemas intramatemáticos y extramatemáticos.", "4 horas", "https://www.confiedy.com/images/courses/courses11.jpg", "5", "Fundamentos de Cálculo", 1);

INSERT INTO confiedy_ui.curso
(id,ciclo, codigo, descripcion, duracion, imagen_curso, maximo_estudiantes, nombre, universidad_id)
VALUES(12,"1","1FIS01","Se aborda de manera teórico-práctica la mecánica de la partícula, profundizando en los temas de cinemática y dinámica; para este fin, se realizan operaciones con magnitudes escalares y vectoriales. En cinemática, se estudian temas de movimiento rectilíneo, casos de velocidad o aceleración constantes, cuerpos en caída libre y su representación gráfica en el tiempo, así como el movimiento de proyectiles. En dinámica, se desarrollan las tres leyes de Newton, los conceptos de masa y peso, y la fuerza de rozamiento. Finalmente, se generan espacios de aprendizaje para la aplicación de los conceptos básicos de Trabajo y Energía.", "4 horas", "https://www.confiedy.com/images/courses/courses5.jpg", "5", "Fundamentos de Física", 1);

INSERT INTO confiedy_ui.curso
(id,ciclo, codigo, descripcion, duracion, imagen_curso, maximo_estudiantes, nombre, universidad_id)
VALUES(13,"1","FIL108"," Es una asignatura fundamental para la formación humana e intelectual del estudiante. Busca introducirlo a los problemas filosóficos, suscitando la reflexión sobre el origen y desarrollo de las principales interrogantes del pensamiento occidental. Abarca dos períodos en la historia del pensamiento: la Antigüedad y el Medioevo, y tiene un enfoque tanto histórico como sistemático. Se abordarán los problemas filosóficos mostrando su génesis y sus transformaciones, pero también se espera que los alumnos puedan entender la relevancia actual de estas interrogantes.", "4 horas", "https://www.confiedy.com/images/courses/courses5.jpg", "5", "Temas de Filosofía Antigua y Medieval", 1);

INSERT INTO confiedy_ui.curso
(id,ciclo, codigo, descripcion, duracion, imagen_curso, maximo_estudiantes, nombre, universidad_id)
VALUES(14,"1","FIL109"," El curso busca, por un lado, suscitar la reflexión filosófica en torno a los principales problemas e interrogantes del pensamiento moderno a través de las obras que los determinan, en particular, las de Descartes, Kant y Hegel. Por otro lado, se espera que el estudiante adquiera una conciencia crítica frente a la tradición filosófica moderna en la cual se asienta la cultura contemporánea. Se pondrá énfasis en la problemática epistemológica que caracteriza a este período y su relación con la filosofía práctica: Ética, Política e Historia.", "4 horas", "https://www.confiedy.com/images/courses/courses1.jpg", "5", " Temas de Filosofía Moderna", 1);

INSERT INTO confiedy_ui.curso
(id,ciclo, codigo, descripcion, duracion, imagen_curso, maximo_estudiantes, nombre, universidad_id)
VALUES(15,"1","FIL142"," El curso consiste en una introducción a los principales problemas e interrogantes de la Filosofía Contemporánea. Estos aparecen determinados tanto por una radicalización ambigua como por una profunda puesta en cuestión de los presupuestos filosóficos heredados de la época moderna. Se abordarán algunas de las principales corrientes del pensamiento occidental entre mediados del siglo XIX y el siglo XX, introduciendo a la lectura de los textos más representativos.", "4 horas", "https://www.confiedy.com/images/courses/courses2.jpg", "5", " Temas de Filosofía Contemporánea", 1);

INSERT INTO confiedy_ui.curso
(id,ciclo, codigo, descripcion, duracion, imagen_curso, maximo_estudiantes, nombre, universidad_id)
VALUES(16,"1","FIL122"," El curso busca introducir a la problemática filosófica de la acción y de la relación entre el bien y la felicidad. Se tomará en cuenta los momentos históricos en que se forman los distintos enfoques y se presentarán los planteamientos que caracterizan a la ética contemporánea." , "4 horas", "https://www.confiedy.com/images/courses/courses3.jpg", "5", " Ética", 1);

INSERT INTO confiedy_ui.curso
(id,ciclo, codigo, descripcion, duracion, imagen_curso, maximo_estudiantes, nombre, universidad_id)
VALUES(17,"1","1HIS16"," Los procesos históricos más importantes del siglo XX es el tema de este curso. Se trata de que, a partir de un enfoque temático y comparativo, el alumno comprenda el siglo XX en su totalidad, sin perder de vista su incidencia en la historia peruana y latinoamericana. Para ello, se estudiarán los grandes momentos de la historia contemporánea a través de los siguientes temas: se inicia con la industrialización, la expansión del capitalismo y el imperialismo en el mundo a partir de 1870, para enfocarse en la Primera Guerra Mundial y la Revolución rusa de 1917; luego, se estudia el mundo entreguerras, la Gran Depresión, el auge de los totalitarismos y la Segunda Guerra Mundial; se trata la Guerra Fría y el papel de los EEUU y la URSS entre 1945 y 1980. Asimismo, se abarcarán procesos históricos como la descolonización de África, la situación de China y Japón en el panorama mundial, y los conflictos del Medio-Oriente, para finalizar con la globalización y el impacto de los avances científicos y tecnológicos a fines del siglo XX." , "4 horas", "https://www.confiedy.com/images/courses/courses4.jpg", "5", " Historia Mundial del Siglo XX", 1);

INSERT INTO confiedy_ui.curso
(id,ciclo, codigo, descripcion, duracion, imagen_curso, maximo_estudiantes, nombre, universidad_id)
VALUES(18,"1","1HIS18","Los procesos históricos más importantes que se dieron en el Perú entre 1900 y la década de 1980 es el tema del curso. Se busca que, a partir de un enfoque temático y comparativo con la historia latinoamericana y mundial, entender el devenir histórico peruano. Para ello, se estudiarán los procesos políticos, sociales, económicos y culturales más importantes que se dieron en la historia peruana a partir de diferentes momentos: el auge y caída de la República Aristocrática, el Oncenio de Leguía, los periodos de militarismo y el civilismo, el gobierno revolucionario de Velasco y la vuelta a la democracia." , "4 horas", "https://www.confiedy.com/images/courses/courses5.jpg", "5", " Historia del Perú en el Siglo XX", 1);

INSERT INTO confiedy_ui.curso
(id,ciclo, codigo, descripcion, duracion, imagen_curso, maximo_estudiantes, nombre, universidad_id)
VALUES(19,"1","1ARQ07","El área donde hoy en día se encuentra el Perú es una de las  seis áreas culturales en el mundo en las que surgió de manera independiente la “civilización”. Al igual que en Mesopotamia, Egipto, el valle del Indo, China y Mesoamérica, en los Andes Centrales surgieron formaciones políticas y económicas complejas de carácter estatal que fueron el resultado de procesos históricos y sociales particulares. Este curso explora tales procesos desde el punto de vista de la arqueología utilizando modelos derivados de diferentes disciplinas de las ciencias históricas y sociales." , "4 horas", "https://www.confiedy.com/images/courses/courses1.jpg", "5", "Prehistoria y Civilizaciones del Perú", 1);

INSERT INTO confiedy_ui.curso
(id,ciclo, codigo, descripcion, duracion, imagen_curso, maximo_estudiantes, nombre, universidad_id)
VALUES(20,"1","1HIS19","La historia del Perú desde el surgimiento de la civilización andina hasta fines del siglo XVIII es el tema del curso. Se tratarán los logros de las culturas anteriores a los Incas y el Tahuantinsuyo, la conquista española en el siglo XVI y el Virreinato del Perú durante los siglos XVII y XVIII. Se pondrá especial énfasis en temas como la conformación de la sociedad colonial, las características del mundo cultural y religioso, la configuración del aparato político y estatal, el funcionamiento de la economía y la relación que se estableció entre el virreinato peruano y la monarquía española. Finalmente, se analizarán las transformaciones económicas, sociales, militares, políticas y culturales producidas por las reformas borbónicas y el desarrollo de los movimientos sociales que culminaron con la rebelión de Túpac Amaru II en 1780." , "4 horas", "https://www.confiedy.com/images/courses/courses2.jpg", "5", "Historia del Perú Antiguo y Colonial", 1);

INSERT INTO confiedy_ui.curso
(id,ciclo, codigo, descripcion, duracion, imagen_curso, maximo_estudiantes, nombre, universidad_id)
VALUES(21,"1","1HIS20","El curso estudiará la historia del Perú durante la Independencia y la República hasta 1980 aproximadamente. Se iniciará con la crisis del sistema colonial en el siglo XVIII y las fases, características y balance del proceso de independencia del Perú, para luego analizar los procesos políticos, sociales, económicos y culturales más importantes que se dieron a lo largo de los siglos XIX y XX. Se enfocará al Perú insertándolo en los procesos históricos latinoamericanos y mundiales, con especial énfasis en el papel que ha cumplido el país en el desarrollo continental en sus dos siglos de vida republicana hasta 1968 aproximadamente." , "4 horas", "https://www.confiedy.com/images/courses/courses3.jpg", "5", "Historia del Perú Republicano", 1);

INSERT INTO confiedy_ui.curso
(id,ciclo, codigo, descripcion, duracion, imagen_curso, maximo_estudiantes, nombre, universidad_id)
VALUES(22,"1","1HIS22","El desarrollo político, social, económico y cultural de la historia peruana desde 1970 hasta la actualidad es el tema del curso. Se abordarán los cambios producidos en el país desde el gobierno militar de Velasco hasta la actualidad. Entre los procesos históricos más importantes, tenemos: los cambios producidos durante el gobierno militar, la transición hacia la democracia, los gobiernos Fujimori, el terrorismo y el conflicto armado interno, la corrupción y el narcotráfico, la Comisión de la Verdad, Paz y Reconciliación, etc. Los temas tratados se estudiarán no solo centrándose en la coyuntura, sino con una perspectiva de larga duración o de largo plazo, propia de la historia. Como el período de análisis será el tiempo presente, también se estudiarán los problemas teóricos y metodológicos que suponen el estudio histórico del presente y la construcción de la memoria, poniendo énfasis en la memoria del periodo de violencia que vivió el Perú entre 1980 y 2000.", "4 horas", "https://www.confiedy.com/images/courses/courses4.jpg", "5", "Historia del Perú: Presente y Memoria", 1);

INSERT INTO confiedy_ui.curso
(id,ciclo, codigo, descripcion, duracion, imagen_curso, maximo_estudiantes, nombre, universidad_id)
VALUES(23,"1","1ARQ10"," El curso se centra en las principales civilizaciones del mundo: Mesopotamia, Egipto, el valle del Indo, China, Mesoamérica y los Andes. Se abordará, de manera comparativa, el problema de los orígenes de la “civilización”, enfatizando el estudio de los procesos económicos, políticos, militares e ideológicos que interactuaron de diferentes maneras, en cada uno de estos casos, hasta resultar en el surgimiento de la “civilización” o formas políticas y económicas complejas de carácter estatal. El curso tiene por objeto familiarizar a los alumnos con los conceptos de la prehistoria y con las maneras de reconstruir el pasado a partir de fuentes materiales.", "https://www.confiedy.com/images/courses/courses11.jpg", "5", "Prehistoria y Civilizaciones del Mundo", 1);

INSERT INTO confiedy_ui.curso
(id,ciclo, codigo, descripcion, duracion, imagen_curso, maximo_estudiantes, nombre, universidad_id)
VALUES(24,"1","HIS113"," El objetivo del curso es ofrecer una visión panorámica de la historia occidental desde la Antigüedad hasta la formación del mundo moderno en los siglos XV y XVI, con la finalidad de reconocer los diversos aportes de la historia antigua y medieval a la cultura universal. El curso se centrará en los temas que permitan una mejor comprensión de la evolución de la historia mundial, como los orígenes de la civilización, la formación de la democracia en Grecia, la expansión y decadencia del imperio romano, las bases de la Europa medieval y la génesis del mundo moderno.", "4 horas", "https://www.confiedy.com/images/courses/courses12.jpg", "5", "Historia del Mundo Antiguo y Medieval", 1);

INSERT INTO confiedy_ui.curso
(id,ciclo, codigo, descripcion, duracion, imagen_curso, maximo_estudiantes, nombre, universidad_id)
VALUES(25,"1","HIS114"," El objetivo del curso es ofrecer una visión panorámica de la historia occidental desde la crisis del mundo medieval hasta la formación de la sociedad industrial en el siglo XIX, con la finalidad de entender los orígenes del mundo contemporáneo. De esta manera, se profundizará en temas como la desacralización de la sociedad y la cultura, el surgimiento del Estado moderno, los orígenes del capitalismo, el establecimiento y crisis del Antiguo Régimen y el impacto de la revolución industrial.", "4 horas", "https://www.confiedy.com/images/courses/courses1.jpg", "5", "Historia del Mundo Moderno", 1);

INSERT INTO confiedy_ui.curso
(id,ciclo, codigo, descripcion, duracion, imagen_curso, maximo_estudiantes, nombre, universidad_id)
VALUES(26,"1","1HIS17","Los principales procesos históricos ocurridos en América Latina y el Caribe, entre los siglos  XIX, XX y su proyección al siglo XXI es el tema del curso. Serán objeto de estudio, la formación y desarrollo de los nuevos estados, y los procesos políticos, sociales, económicos y culturales más importantes que se dieron en este espacio, a lo largo de los siglos XIX y XX. Se verán los grandes temas de forma transversal en la historia de algunos países, utilizando las perspectivas comparativa y global." , "4 horas", "https://www.confiedy.com/images/courses/courses2.jpg", "5", "Historia Latinoamericana Contemporánea", 1);

INSERT INTO confiedy_ui.curso
(id,ciclo, codigo, descripcion, duracion, imagen_curso, maximo_estudiantes, nombre, universidad_id)
VALUES(27,"1","1HIS21","Los más significativos procesos de la historia peruana, latinoamericana y mundial en las décadas finales del siglo XX e iniciales del siglo XXI es el tema del curso. Entre los procesos históricos que serán tratados tenemos: el impacto de los avances científicos y tecnológicos, los cambios en el capitalismo mundial y la globalización, los conflictos en Medio Oriente y el terrorismo internacional, etc. Los temas se estudiarán no solo centrándose en la coyuntura, sino con una perspectiva de larga duración o de largo plazo, propia de la historia. Como el período de análisis será el tiempo presente, también se estudiarán los problemas teóricos y metodológicos que suponen el estudio histórico del presente y la construcción de la memoria." , "4 horas", "https://www.confiedy.com/images/courses/courses2.jpg", "5", "Historia Mundial: Presente y Memoria", 1);

INSERT INTO confiedy_ui.curso
(id,ciclo, codigo, descripcion, duracion, imagen_curso, maximo_estudiantes, nombre, universidad_id)
VALUES(28,"1","HIS108"," El objetivo del curso es ofrecer una visión de la Historia del Perú desde el surgimiento de la civilización andina prehispánica hasta la rebelión de Túpac Amaru II. Se buscará comprender ciertos temas fundamentales de la Historia del Perú: la formación de las sociedades pre-incaicas, la aparición del Tahuantinsuyo, el impacto de la colonización española de los Andes, la consolidación del virreinato y los efectos de las reformas borbónicas.", "4 horas", "https://www.confiedy.com/images/courses/courses4.jpg", "5", "Historia del Perú: Formación hasta el Siglo XVIII", 1);

INSERT INTO confiedy_ui.curso
(id,ciclo, codigo, descripcion, duracion, imagen_curso, maximo_estudiantes, nombre, universidad_id)
VALUES(29,"1","HIS120"," El objetivo del curso es ofrecer un panorama del Perú contemporáneo desde la crisis del Oncenio de Leguía hasta nuestros días, con la finalidad de entender el actual perfil de nuestro país. El curso analizará temas como los grupos políticos, el militarismo, la dictadura odriísta, los años 60 y el primer belaundismo, la reforma militar de los 70, la nueva democracia de los 80 y la década del fujimorismo.", "4 horas", "https://www.confiedy.com/images/courses/courses5.jpg", "5", "Historia del Perú Contemporáneo", 1);

INSERT INTO confiedy_ui.curso
(id,ciclo, codigo, descripcion, duracion, imagen_curso, maximo_estudiantes, nombre, universidad_id)
VALUES(30,"1","HIS164"," Presenta los grandes momentos de la historia contemporánea con la finalidad de interpretar el siglo XX a través de los siguientes temas: Europa: 1870-1914, el imperio inglés, la Primera Guerra Mundial, los EEUU: 1865- 1941, la Revolución rusa, la época de Stalin, el fascismo-nazismo, la Segunda Guerra Mundial, la Guerra Fría, los EEUU: 1945-1992, la URSS: 1945-1991, China: siglo XX, la India: siglo XX, Japón: siglo XX, los Conflictos del Medio-Oriente, África: siglo XX, hacia una Aldea Mundial.", "4 horas", "https://www.confiedy.com/images/courses/courses1.jpg", "5", "Historia Universal Contemporánea", 1);

INSERT INTO confiedy_ui.curso
(id,ciclo, codigo, descripcion, duracion, imagen_curso, maximo_estudiantes, nombre, universidad_id)
VALUES(31,"1","HUM133","El curso tiene como propósito que el alumno conozca y emplee las herramientas expresivas básicas para producir textos argumentativos formales, fundamentalmente de opinión. Para alcanzar este fin, el curso está diseñado como un espacio de discusión acerca del discurso argumentativo a partir de un núcleo temático definido cada semestre; al mismo tiempo, se orienta hacia la práctica permanente de la producción de textos. Se incide, de manera crucial, en el proceso de elaboración de un trabajo orientado a sustentar una opinión sobre algún problema específico, en el que concurran la investigación y la argumentación. Se exige la participación del alumno, pues se otorga lugar importante a la presentación y exposición de las propias ideas, la discusión dirigida y el debate.", "4 horas", "https://www.confiedy.com/images/courses/courses2.jpg", "5", "Argumentación", 1);

INSERT INTO confiedy_ui.curso
(id,ciclo, codigo, descripcion, duracion, imagen_curso, maximo_estudiantes, nombre, universidad_id)
VALUES(32,"1","LIN126"," El taller está orientado a mejorar las habilidades del estudiante para la redacción y comprensión de textos académicos. Exigirá la lectura íntegra de un libro de nivel universitario. Además de la comprensión y el análisis detallado del texto, el estudiante se ejercitará en la composición textual, la sintaxis, el manejo correcto de la información y la normativa. El taller no solo estimulará la lectura comprensiva del alumno (fundamentalmente conceptual y metafórica y no meramente descriptiva), sino también lo hará familiarizarse con el uso de gramáticas y diccionarios. Se buscará pues que el estudiante afronte lecturas de largo aliento, discierna los objetivos principales de un texto académico y reconozca la unidad entre forma y contenido. Todo ello estará dispuesto con la finalidad de que mejore su capacidad para la redacción y comprensión de textos académicos.", "4 horas", "https://www.confiedy.com/images/courses/courses3.jpg", "5", "Taller de Escritura e Interpretación de Textos", 1);

INSERT INTO confiedy_ui.curso
(id,ciclo, codigo, descripcion, duracion, imagen_curso, maximo_estudiantes, nombre, universidad_id)
VALUES(33,"1","INT130"," El curso de Investigación académica presupone los contenidos del curso de Argumentación y tiene como objetivo la redacción de una monografía, es decir, un trabajo de investigación académica de mediana extensión en el cual se plantea un problema de investigación y se busca justificar una hipótesis de trabajo. El curso se divide en teoría y práctica, siendo la teoría el espacio donde se planteará la estrategia de planificación y de ejecución del trabajo, mientras que en las horas de práctica se desarrollará, en sus líneas generales, y paulatinamente, el producto final. Temáticamente, el curso se divide en planeamiento y ejecución. Los temas que se tocarán como parte de la estrategia de planificación de la investigación son: Sentido de la investigación académica, criterios de búsqueda bibliográfica, delimitación del tema, planteamiento del problema, hipótesis de trabajo, objetivos, indicadores de logro y esquema de trabajo. Todos ellos convergerán en un producto que se entregará como parte de la evaluación parcial y que es llamado Plan de trabajo. Los temas que se tocarán como parte de la ejecución del trabajo son: Recopilación y manejo de información (uso de fichas de trabajo, notas a pie de página y citas), redacción de capítulos, conclusiones e introducción. El curso está diseñado para que la investigación que se realice se enmarque dentro de los intereses académicos de los estudiantes, principalmente dentro de los futuros horizontes de trabajo intelectual de sus Facultades de destino.", "4 horas", "https://www.confiedy.com/images/courses/courses4.jpg", "5", "Investigación Académica", 1);

INSERT INTO confiedy_ui.curso
(id,ciclo, codigo, descripcion, duracion, imagen_curso, maximo_estudiantes, nombre, universidad_id)
VALUES(34,"6","DEC281"," El curso Derechos Reales se imparte en el segundo ciclo de la carrera y es el primero que profundiza en el análisis de las instituciones jurídicas civiles. Combina sesiones teóricas de análisis de la doctrina, legislación y jurisprudencia con la solución de casos. Su finalidad es el estudio de los principales derechos sobre las cosas y los conflictos éticos que de ello surgen, por lo cual se vincula a las competencias marco ético de la profesión y excelencia académica. Versa
sobre las nociones de derecho y garantía real, sus características, los elementos que distinguen a cada una de ellas, los modos de adquisición y extinción y su evolución. En específico, estudia las instituciones jurídicas de propiedad, posesión, usufructo, uso y habitación", "4 horas","https://www.confiedy.com/images/courses/courses5.jpg", "5", "Reales", 1);

INSERT INTO confiedy_ui.curso
(id,ciclo, codigo, descripcion, duracion, imagen_curso, maximo_estudiantes, nombre, universidad_id)
VALUES(35,"7","DEC283"," El curso Contratos se imparte en el tercer ciclo de la carrera y es un curso de razonamiento jurídico civil. Comprende sesiones teóricas que se desarrollan a partir de la discusión de casos y jurisprudencia relevante en la materia. Sus resultados contribuyen al desarrollo de conocimientos y habilidades en el estudiante que les permite analizar y aplicar las instituciones referidas al derecho de los contratos a problemas reales. De este modo, contribuye a las competencias excelencia académica y marco ético de la profesión. Los temas que aborda son la relevancia del consenso para la producción de efectos jurídicos, el acto jurídico, la noción de contrato, su formación, elementos, principios y extinción, así como la evolución de estas instituciones. Además, abordará de forma particular, el contrato de compraventa", "4 horas","https://www.confiedy.com/images/courses/courses11.jpg", "5", "Contratos", 1);

INSERT INTO confiedy_ui.curso
(id,ciclo, codigo, descripcion, duracion, imagen_curso, maximo_estudiantes, nombre, universidad_id)
VALUES(36,"7","DEC284"," Familia es un curso especializado de derecho civil que se imparte en el tercer ciclo de la carrera. Si bien las sesiones tienen un alto contenido teórico de análisis normativo y doctrinario, comprenden el debate permanente de casos y jurisprudencia nacional y extranjera. Busca que el alumno esté en la capacidad de analizar y aplicar las instituciones socio jurídicas del derecho de familia y, en especial, de la sociedad conyugal a la solución de los casos reales. Así, contribuye a las competencias de Excelencia Académica y Marco Ético de la profesión. Versa sobre la noción de familia, los diversos tipos de familia que se producen en la sociedad y los que están recogidos en la ley peruana. En ese contexto, se estudia especialmente la unión de hecho y el matrimonio, su evolución, sus elementos de validez y extinción, así como sus efectos personales y patrimoniales. ","4 horas", "https://www.confiedy.com/images/courses/courses12.jpg", "5", "Familia", 1);

INSERT INTO confiedy_ui.curso
(id,ciclo, codigo, descripcion, duracion, imagen_curso, maximo_estudiantes, nombre, universidad_id)
VALUES(37,"1","LIN146"," El curso ofrece una perspectiva teórica para examinar la dimensión social e histórica de la lengua. Su objetivo particular está dirigido al Perú y su diversidad lingüística y cultural. Ello significa que el curso contemplará puntualmente los fenómenos de variación lingüística y uso de la lengua en el caso particular peruano.", "4 horas", "https://www.confiedy.com/images/courses/courses4.jpg", "5", "Familia", 1);

INSERT INTO confiedy_ui.curso
(id,ciclo, codigo, descripcion, duracion, imagen_curso, maximo_estudiantes, nombre, universidad_id)
VALUES(38,"2","1MAT06"," Es un curso teórico-práctico que aporta al logro de la competencia general aprender a aprender, puesto que desarrolla la capacidad de aplicar conocimientos de matemáticas para la resolución de problemas. El curso se centra en el estudio del cálculo diferencial de funciones reales de variable real y sus aplicaciones a las ciencias. En este curso, se desarrolla los conceptos y propiedades fundamentales de límites, continuidad, derivada, integral indefinida y ecuaciones diferenciales ordinarias de primer orden en la solución de diversos ejercicios y problemas intramatemáticos y extramatemáticos.", "4 horas","https://www.confiedy.com/images/courses/courses1.jpg", "5", "Cálculo Diferencial", 1);

INSERT INTO confiedy_ui.curso
(id,ciclo, codigo, descripcion, duracion, imagen_curso, maximo_estudiantes, nombre, universidad_id)
VALUES(39,"3","1MAT06","Es un curso teórico-práctico que aporta al logro de la competencia general aprender a aprender, ya que desarrolla la capacidad de aplicar conocimientos de matemáticas para la resolución de problemas. El curso se centra en el estudio del cálculo integral de funciones reales de una variable y sus aplicaciones a las ciencias e ingeniería. En el curso, se aplica los conceptos de integral definida de una función y los métodos básicos de integración para la obtención de la integral que sirven para el cálculo de áreas de regiones planas, volúmenes de sólidos de revolución, centros de masa de láminas delgadas y homogéneas, longitudes de curvas en coordenadas cartesianas y polares, cálculo aproximado de integrales usando polinomios de Taylor, y resolución de ecuaciones diferenciales ordinarias lineales con coeficientes constantes con aplicaciones a la física. Además, se generaliza el concepto de la integral al cálculo de integrales impropias y el estudio de su convergencia.", "4 horas","https://www.confiedy.com/images/courses/courses2.jpg", "5", "Cálculo Integral", 1);

-- CURSOS UNIVERSIDAD DE LIMA

INSERT INTO confiedy_ui.curso
(id,ciclo, codigo, descripcion, duracion, imagen_curso, maximo_estudiantes, nombre, universidad_id)
VALUES(100,"2","6503", "La asignatura tiene como propósito desarrollar tanto las habilidades orientadas al razonamiento lógico como las competencias para el análisis, la abstracción, la generalización y la asociación dirigidas a la solución de problemas relacionados con la Ingeniería, mediante el uso del cálculo diferencial e integral en una variable real. Comprende el estudio de: funciones trigonométricas, límites y continuidad de funciones, derivadas de funciones, aplicaciones de la derivada, integral indefinida de una función.", "4 horas", "https://www.confiedy.com/images/courses/courses4.jpg", "5", "Cálculo 1", 3);

INSERT INTO confiedy_ui.curso
(id,ciclo, codigo, descripcion, duracion, imagen_curso, maximo_estudiantes, nombre, universidad_id)
VALUES(101,"1","6382", "La asignatura desarrolla en los estudiantes tanto las habilidades orientadas al pensamiento lógicocomo las competencias para el análisis, la abstracción, la generalización y la asociación dirigidasa la solución de problemas. Comprende el estudio del sistema de los números reales, la recta en el plano, cónicas y funciones reales.", "4 horas", "https://www.confiedy.com/images/courses/courses8.jpg", "5", "Matemática Básica", 3);

INSERT INTO confiedy_ui.curso
(id,ciclo, codigo, descripcion, duracion, imagen_curso, maximo_estudiantes, nombre, universidad_id)
VALUES(102,"2","6502", "La asignatura tiene como propósito desarrollar aspectos fundamentales del método estadístico como herramienta para el buen uso de la información orientada a la toma de decisiones en los negocios. Comprende el estudio de: nociones básicas de la estadística, fuentes y técnicas de recopilación de datos, técnicas de procesamiento y presentación de datos, y medidas estadísticas de resumen con análisis exploratorio de datos y técnicas de conteo.", "4 horas","https://www.confiedy.com/images/courses/courses3.jpg", "5", "Estadística Básica para los Negocios", 3);

INSERT INTO confiedy_ui.curso
(id,ciclo, codigo, descripcion, duracion, imagen_curso, maximo_estudiantes, nombre, universidad_id)
VALUES(103,"2","6337", "La asignatura tiene como propósito desarrollar las habilidades orientadas al razonamiento lógico, las competencias para el análisis, la abstracción, la generalización y la síntesis dirigidas a la solución de problemas del cálculo diferencial e integral de funciones reales de variable real, relacionados con el campo de los negocios. Comprende el estudio de: construcción de modelos matemáticos y límites, la derivada y sus aplicaciones, funciones trascendentes, la integral y sus aplicaciones a los negocios.", "4 horas", "https://www.confiedy.com/images/courses/courses8.jpg", "5", "Matemática Aplicada para los Negocios", 3);

-- CURSOS UNIVERSIDAD DEL PACIFICO

INSERT INTO confiedy_ui.curso
(id,ciclo, codigo, descripcion, duracion, imagen_curso, maximo_estudiantes, nombre, universidad_id)
VALUES(200,"0","134654", "Es un curso que carece de creditaje y es obligatorio para los estudiantes que no cursaron bachillerato internacional ni aprobaron la prueba de exoneración. Sus contenidos son los siguientes: lógica y conjuntos; fundamentos de álgebra; tópicos de aritmética, de geometría analítica y de trigonometría.", "4 horas", "https://www.confiedy.com/images/courses/courses1.jpg", "5", "Nivelación en Matemáticas", 4);

INSERT INTO confiedy_ui.curso
(id,ciclo, codigo, descripcion, duracion, imagen_curso, maximo_estudiantes, nombre, universidad_id)
VALUES(201,"1","138649", " Este curso de primer ciclo introduce al alumno al estudio de herramientas matemáticas para su desarrollo profesional. Consta de 5 créditos y son prerrequisitos para cursarlo haber aprobado el curso de Nivelación de matemáticas o, en su defecto, el examen exoneratorio de dicho curso. El curso contribuye al desarrollo de la competencia de pensamiento crítico y al siguiente resultado asociado a dicha competencia: “1.4: Resuelve problemas utilizando herramientas matemáticas básicas.” Sus contenidos son: lógica y conjuntos; números reales; convergencia; geometría analítica; álgebra lineal y funciones.", "4 horas", "https://www.confiedy.com/images/courses/courses2.jpg", "5", "Matemáticas 1", 4);

INSERT INTO confiedy_ui.curso
(id,ciclo, codigo, descripcion, duracion, imagen_curso, maximo_estudiantes, nombre, universidad_id)
VALUES(202,"2","131650", "Es un curso de segundo ciclo y tiene 5 créditos. Es prerrequisito para cursarlo haber aprobado Matemáticas I. Este curso contribuye al desarrollo de la competencia de pensamiento crítico y al siguiente resultado asociado a dicha competencia: “1.4: Resuelve problemas utilizando herramientas matemáticas básicas.” Sus contenidos son los siguientes: límites de funciones y continuidad, derivadas, funciones de varias variables e integrales.", "4 horas", "https://www.confiedy.com/images/courses/courses3.jpg", "5", "Matemáticas 2", 4);

INSERT INTO confiedy_ui.curso
(id,ciclo, codigo, descripcion, duracion, imagen_curso, maximo_estudiantes, nombre, universidad_id)
VALUES(203,"3","130233", " Matemáticas III es un curso obligatorio para las carreras de Economía y de Finanzas. Tiene como requisito Matemáticas II (131650) y sirve como requisito para los cursos de Matemáticas IV (130229) y Econometría I (130424). Esta sección es dictada en inglés. El curso proporciona a los estudiantes conceptos claves de álgebra matricial y de cálculo multivariado, con el propósito de incorporarlos plenamente en el instrumental matemático más utilizado en el análisis económico estático y en el desarrollo de técnicas econométricas. Además, se introduce a los estudiantes al análisis dinámico, univariado y multivariado, y sus aplicaciones en las teorías económica, financiera y econométrica.", "4 horas", "https://www.confiedy.com/images/courses/courses4.jpg", "5", "Matemáticas 3", 4);

INSERT INTO confiedy_ui.curso
(id,ciclo, codigo, descripcion, duracion, imagen_curso, maximo_estudiantes, nombre, universidad_id)
VALUES(204,"4","130229", "El curso de Matemáticas IV pretende adiestrar a los alumnos en el uso de las principales técnicas de programación matemática (optimización estática) y los métodos básicos de optimización dinámica: cálculo de variaciones, control óptimo y programación dinámica. Asimismo, se busca familiarizarlos con las aplicaciones económicas más frecuentes de estos métodos, fortaleciendo la competencia de pensamiento crítico.", "4 horas", "https://www.confiedy.com/images/courses/courses8.jpg", "5", "Matemáticas 4", 4);

INSERT INTO confiedy_ui.curso
(id,ciclo, codigo, descripcion, duracion, imagen_curso, maximo_estudiantes, nombre, universidad_id)
VALUES(205,"2","130230", "Es un curso de segundo ciclo y tiene 4 créditos. Es prerrequisito para cursarlo haber aprobado Matemáticas I. Este curso contribuye al desarrollo de la competencia de pensamiento crítico y al siguiente resultado asociado a dicha competencia: “1.4: Resuelve problemas utilizando herramientas matemáticas básicas.” Sus contenidos son los siguientes:  límites de funciones y continuidad, derivadas, funciones de varias variables e integrales.", "4 horas", "https://www.confiedy.com/images/courses/courses11.jpg", "5", "Matemáticas para los Negocios", 4);

INSERT INTO confiedy_ui.curso
(id,ciclo, codigo, descripcion, duracion, imagen_curso, maximo_estudiantes, nombre, universidad_id)
VALUES(206,"4","132641", "Economía General I es una asignatura introductoria orientada a proveer los fundamentos de la microeconomía, por lo que es la base para cursos posteriores de economía. El curso está centrado en el aprendizaje de los principios que, según la teoría económica, rigen el funcionamiento de los mercados y las decisiones que toman los individuos, familias, empresas y gobierno para lograr sus objetivos, relacionados con la asignación de recursos. De este modo, el aprendizaje de los contenidos del curso requiere intuición, capacidad de abstracción y una base matemática mínima de aritmética, álgebra y geometría analítica básica para poder representar en gráficos situaciones concretas y cotidianas. El curso aporta al desarrollo de las competencias de pensamiento crítico y trabajo en equipo.", "4 horas", "https://www.confiedy.com/images/courses/courses12.jpg", "5", "Economía General 1", 4);
